### ISSUE TITLE
Import{Batch,Namespace}Specifier identifier field name

### ISSUE THREAD

**Issue by impinball** [estree/estree#12]
**Note: this issue has nothing to do with the title of the actual node itself. Any discussion of that is better suited to issue #9.**

Here's a quick visual description of the problem.

```coffee
# Acorn
type: 'ImportBatchSpecifier'
name: Identifier('foo')

# Esprima
type: 'ImportNamespaceSpecifier'
id: Identifier('foo')
```

Shouldn't we pick either `.id` or `.name`?

**Comment by caridy** [comment]
Yes, they should be aligned, but they should align with `ImportSpecifier` as well. Essentially, my take on this is that `name` references to the named export from source, while `id` references to the local identifier. This means that `ImportNamespaceSpecifier` and `ImportBatchSpecifier` will never have a `name` since they do not reference to a specific named export from source.

**Comment by caridy** [comment]
...this pattern also aligns with `ExportDeclaration` where `id` references to the local binding that is going to be exported, and `name` references to the named export specifier.

**Comment by mikesherov** [comment]
@RReverser, thoughts? Seems like we may want to go with what Esprima currently has...

**Comment by sebmck** [comment]
@mikesherov #35 introduces a `ImportNamespaceSpecifier` node so this, #11 and #9 can safely be closed.

**Comment by mikesherov** [comment]
Got it, thanks!
