### ISSUE TITLE
Proposal to potentially incorporate changes to existing nodes

### ISSUE THREAD

**Issue by hzoo** [estree/estree#120]
I'm wondering if some of the changes in Babel would be considered for ESTree? This would be for existing nodes, so I can understand this would be not backwards compatible (I don't know about the previous conversations so maybe this kind of thing was discussed before).

If it's not up for discussion, then feel free to close! Figured I would ask.

Some changes: (Can check by switching parsers in [ASTExplorer](http://astexplorer.net/#/uL2gtdFAGt))
- `Literal` was "underloaded' and split into their own nodes based on type (`BooleanLiteral`, `RegExpLiteral`, `NumericLiteral`, `StringLiteral`, `NullLiteral`).
- `MethodDefinition` was renamed to `ClassMethod`
- `Property` was renamed to `ObjectProperty` or `ObjectMethod`
- The `value` property's properties in `FunctionExpression` for `ClassMethod`, `ObjectProperty`, and `ObjectMethod` is coerced/brought into the main method node.

@markelog / @mdevils were [noticing](https://github.com/cst/cst/issues/86) that object methods are producing an AST which violates ESTree rules (`#2`)?
i.e. `FunctionExpression` has a generator flag which is computed using data which is out of `FunctionExpression`’s scope and range.

**Comment by mdevils** [comment]
I would say that was a huge mistake to represent object method (`{ x() {} }`) as a combination of `Property` and `FunctionExpression` because it broke `#2` rule (see #5). What we currently have is the situation where those nodes (`Property` and `FunctionExpression`) has ambiguous responsibility.

See this example:

```js
{
            // Property.id      FunctionExpression.params
    *       methodName    (x, y, z)               { ; }
//  ^ FunctionExpression.generator          ^ FunctionExpression.body
}
```

As you can see, even though `Property` contains `FunctionExpression`, in fact `FunctionExpression` surrounds `Property`.

**Comment by RReverser** [comment]
@hzoo Please note the [Philosophy](https://github.com/estree/estree#philosophy) section in the README:

> 1. Backwards compatible: Non-additive modifications to existing constructs will not be considered unless immense support is in favor of such changes. (eg. #65)

The changes you're proposing seem to break backward compatibility, and thus not really acceptable for all the tools that depend on ESTree out there.

**Comment by mdevils** [comment]
@RReverser what do we do when we have two conflicting rules from the Philosophy section for one case? :)

**Comment by RReverser** [comment]
@mdevils I don't really see how is `#2` violated by function knowing that it's generator. This information, unlike conciseness, definitely belongs to the function, not to the object property, as changes semantics of function execution, so function shouldn't look up at it's parent to know e.g. whether `yield` is supported or not.

**Comment by mdevils** [comment]
@RReverser then please tell me which tokens belong to which node. If we look at both `esprima` and `babel5`, we can clearly see that `FunctionExpression` starts with the first round parenthesis `(` and generator star (`*`) is out `FunctionExpression`'s range.

**Comment by RReverser** [comment]
Basically `#2` (contextless) means "can you extract this node out of it's context and not lose important information".

**Comment by RReverser** [comment]
@mdevils Tokens question belongs more to CST (#41, #107) than to AST, AST doesn't define per-token rules or whitespace/punctuator handling.

**Comment by RReverser** [comment]
As for the generator star - yes, logically it belongs to the function expression, although it's hard to express in location range because in that case we would also accidentally grab identifier, which belongs to the property not function. But anyway, let's move location and tokens discussion to the proper issue.

**Comment by mdevils** [comment]
@RReverser BTW it's really good to keep backwards compatibility, but only when you have a procedure to correctly break it when necessary.

**Comment by mdevils** [comment]
@RReverser talking about contextless. You cannot render `FunctionExpression` without knowing it's parent in this case. Does this correspond to the lack of contextless AST implementation?

**Comment by RReverser** [comment]
@mdevils It was necessary when ESTree was created and ES6 representations started to diverge. Other than that, we don't want to break all the supporting tools (SpiderMonkey, UglifyJS, Esprima, ESLint, Acorn, recast, ast-types, jscodeshift and many others) "just because it's more convenient". Nothing new, really, we just follow "don't break the Web" rule that is applicable to other areas (incl. ECMAScript itself).

**Comment by RReverser** [comment]
> You cannot render FunctionExpression without knowing it's parent in this case.

How so? I can easily take its node and use in another expression (say, RHS of assignment).

**Comment by mdevils** [comment]
@RReverser Imagine you are developing ESTree renderer and you just go down the tree and render every node. In this situation you can't render `FunctionExpression` correctly without the knowledge that it's in `MethodDefinition`. Because `FunctionExpression` is `function id? () {}` and method definition requires just `() {}`.

**Comment by RReverser** [comment]
@mdevils Note that `Property` in this case is valid ES5 Property, so you can still render it as `propertyName: function *() {}` if you don't want to keep context, and it will still work.

Otherwise, if you care about pretty-printing or validation, then obviously such use-cases need to keep around own context that they care about - e.g. you can't tell whether `return` is valid unless you know whether you're inside of the function, but this doesn't mean that `ReturnStatement` needs `inFunction` property, right? (otherwise you would also violate duplication principle). So AST keeps all the important information in the nodes it belongs to, giving every tool ability to play with it in any way it needs to (whether it cares about context details or not), yet not being verbose and staying minimal at the same time.

**Comment by mdevils** [comment]
@RReverser that's why I have consciously provided `MethodDefinition` in this example as you cannot render method definition using `function` keyword: `class X { method(){} }` works, but `class X { method: function(){} }` won't work.

**Comment by RReverser** [comment]
@mdevils Ah, sorry, didn't notice that you switched to `MethodDefinition` from `Property`, thought it's still about objects.

**Comment by RReverser** [comment]
@mdevils Well, yeah, just another case where you need to keep tool-specific context then. This is a good example, but it follows very original ES5 Property approach with `get`/`set` properties, where you already need context for printing.

**Comment by nzakas** [comment]
Just to offer a related perspective: I agree that we cannot break backwards compatibility. That means we cannot remove existing nodes/properties just in case someone is using them. I also agree that ESTree has some pretty lousy representations for things like methods (I brought up earlier in https://github.com/estree/estree/issues/5 as well). 

Adding new nodes and new properties does not break backwards compatibility. That's why we're able to propose and add new things (and why I'm keen on getting those right to avoid any further ugliness). So adding a node to represent ES7 decorators doesn't break backwards compatibility.

Now here's where things get interesting.

Is introducing a new node type that represents the same thing as an existing node type a backwards-compatible change?

**Comment by RReverser** [comment]
> Is introducing a new node type that represents the same thing as an existing node type a backwards-compatible change?

Personally I believe it is, as (IIUC) it's not an additive change and means that output node type for the same code won't be the expected input type for any existing handlers.

**Comment by mikesherov** [comment]
Agree with @rreverser

**Comment by nzakas** [comment]
I think so, too, just wanted to do the thought experiment.

**Comment by jmm** [comment]
> Is introducing a new node type that represents the same thing as an existing node type a backwards-compatible change?

You're all saying that'd be a backwards-*incompatible* change right?

> Adding new nodes and new properties does not break backwards compatibility. That's why we're able to propose and add new things (and why I'm keen on getting those right to avoid any further ugliness).

Another thing worth discussing here is that this spec is in search of a better way to represent directives (https://github.com/estree/estree/issues/6) and Babel 6 has an explicit representation using new node types and properties.

**Comment by jmm** [comment]
I don't know, I probably misinterpreted and you all meant what you actually said. Let's try this, if you care to: what are your thoughts on the representation of directives in Babel 6 and would it be possible (on paper) to absorb it here?

**Comment by mikesherov** [comment]
Babel 6 is already incompatible with ESTree at this point. It's not all that difficult to imagine many ways to represent directives if you don't care about not breaking BC.

 Replacing the string literal that would represent a directive breaks consumers of ESTree and is not a change we can make. The best we can do is dangle a property off of string literals.

**Comment by RReverser** [comment]
> You're all saying that'd be a backwards-incompatible change right?

Oops, yeah, I misread the original question, so said "I believe it is", but from expanded answer I hope that was clear that I meant it's backwards-*incompatible* IMO.

**Comment by jmm** [comment]
@mikesherov Ok, thanks :) I know Babel AST and ESTree are hopelessly diverged, mainly why I asked was to nail down whether you were all saying the scenario presented before would be BC or breaking, since everybody actually phrased that it would be BC.

@RReverser
> Oops, yeah, I misread the original question, so said "I believe it is", but from expanded answer I hope that was clear that I meant it's backwards-*incompatible* IMO.

Thanks for clarifying. That's indeed what I thought your expanded answer indicated at first, then got unsure.

**Comment by nzakas** [comment]
Fwiw, there is an issue about directives: https://github.com/estree/estree/issues/6

**Comment by mikesherov** [comment]
Seems like we should close this now that Babel is moving towards ESTree compliance.
