### ISSUE TITLE
Please create an ESTree equivalent for Ruby

### ISSUE THREAD

**Issue by icefapper** [estree/estree#130]
Hello; there are a couple parsers for ruby, but all use their own AST formats, all of which are barely readable by a non-computers. Could I ask the maintainers consider 'standardizing' Ruby's AST format, in the same way they did for ECMAScript by creating ESTree?

**Comment by RReverser** [comment]
Sorry, but this is really irrelevant to this repo.

First of all, ESTree appeared on top of several already existing implementations which agreed on one single format (initially created by Mozilla). Your situation sounds different, if you're not a maintainer of language itself and all the tools use own formats, you can't just provide "standard" which everyone should obey just because someone wrote a doc. Unfortunately, that doesn't work so easily.

Second, AST are not really intended to be readable by humans (they can be for the sake of debugging, but that's not a primary goal).

And finally, this is repo for JavaScript AST, which is somewhat irrelevant place to ask for Ruby standards. Perhaps Ruby channels would be more appropriate https://github.com/ruby/ruby.

**Comment by icefapper** [comment]
Thanks for the response!
I have to cede you are right; I actually did ask the folks at ruby at least document Ripper, but their response was that it is being kept undocumenteed intentionally, because, "ruby is a moving target."

Thanks again though!
