### ISSUE TITLE
`RestProperty` should have a pattern `argument`, not an expression

### ISSUE THREAD

**Issue by isiahmeadows** [estree/estree#145]
It seems odd for `RestProperty` to take an `Expression` as its argument, when it's the `...rest` in `const {x, y, ...rest} = object`.

**Comment by RReverser** [comment]
Indeed, it's just an experimental definition by @hzoo, feel free to send a PR.

Also, I think we don't necessarily need to introduce new node types here and could instead reuse `RestElement` and `SpreadElement` from es2015 definitions.

**Comment by ariya** [comment]
I am with the reuse of `RestElement`, unless there's a significant difference that warrants the distinction.

**Comment by ariya** [comment]
It is useful to notice that Babylon calls it `RestProperty` and Espree calls it `ExperimentalRestProperty`. Also, it is aligned with the regular object property that is called only `Property`.

As for rest property's argument, I do believe it should be a pattern instead (just like in rest element).

**Comment by hzoo** [comment]
For more context it was also just `RestElement` before but was separated out (similar to Literal -> StringLiteral etc in Babel 6) into `RestProperty`.

Espree has `ExperimentalRestProperty` because ESLint isn't committing to stage < 4 features but wanted to include it in as an exception due to React/JSX.

I think it makes it clearer that Property -> objects and Element is for arrays?

but yeah 👍

**Comment by RReverser** [comment]
Well if we just want to have separate node names in each context, which are otherwise same, then yeah, but it doesn't make much sense IMO, given that they have same structure and purpose (see # 2 in [Philosophy](https://github.com/estree/estree#philosophy)).

**Comment by nzakas** [comment]
Unless there's a difference in syntax (which I don't think there is), I think RestElement makes sense. Part of why Espree has the super verbose node type was because we wanted to prepare people for the possibility that the node type might change. 

Would this also apply to SpreadElement vs. SpreadProperty?

**Comment by RReverser** [comment]
@nzakas Yeah, as I said above, I think it applies to both

> could instead reuse `RestElement` and `SpreadElement` from `es2015` definitions
