### ISSUE TITLE
Private Class Field representation

### ISSUE THREAD

**Issue by loganfsmyth** [estree/estree#154]
Some discussion in https://github.com/babel/babylon/pull/260 currently, figured I'd raise it over here before we accept anything.

Current proposal there being
```
interface PrivateName <: Expression, Pattern {
  type: "PrivateName";
  name: string;
}

interface ClassPrivateProperty <: Node {
  type: "ClassPrivateProperty";
  key: Identifier;
  value: Expression;
}

extend interface ClassBody {
  body: [ MethodDefinition | ClassPrivateProperty ]
}
```

I'm not sure I love the duplication between `PrivateName` and `Identifier` so perhaps `name` could be an `Identifier` instead of a string.

Keep in mind that both `this.#priv = 1234` and `#priv = 1234` are allowed, otherwise there'd be the potential for `MemberExpression` to just have a `private: boolean` property.

**Comment by gibson042** [comment]
Thanks! My (non-authoritative) comments, from the bottom up:
> extend interface ClassBody {
  body: [ MethodDefinition | ClassPrivateProperty ]
}

I think `PrivateProperty` would be better than `ClassPrivateProperty` (among other reasons, the concept could logically be generalized beyond classes).

> interface ClassPrivateProperty <: Node {
  type: "ClassPrivateProperty";
  key: Identifier;
  value: Expression;
}

This could inherit from `Property` instead of `Node` (though that would mostly be an organizational detail at this point).

> interface PrivateName <: Expression, Pattern {
  type: "PrivateName";
  name: string;
}

For internal consistency, I'd prefer
```
interface PrivateIdentifier <: Identifier {
    type: "PrivateIdentifier";
}
```

**Comment by hzoo** [comment]
Realized we never discussed public fields either? Not sure if this should be a separate issue but they are similar.

In Babel right now it's: 

```js
interface ClassProperty <: Node {
  type: "ClassProperty";
  key: Identifier;
  value: Expression;
  computed: boolean;
}
```

Proposal was renamed to "public class fields" https://github.com/tc39/proposal-class-public-fields

**Comment by loganfsmyth** [comment]
Babel appends "Class" I can only assume to avoid potential confusion between objects and classes. For ESTree I suggested it because PrivateProperty vs PublicProperty vs Property isn't necessarily obvious. I suppose we could also overload `kind` on `property` to include `public` and `private` for the class usecase.

No strong feelings really.

**Comment by loganfsmyth** [comment]
> For internal consistency, I'd prefer
> ```
> interface PrivateIdentifier <: Identifier {
>    type: "PrivateIdentifier";
> }
> ```

certainly an option, yup. I was hesitant because I don't think there is currently a precedent for redefining `Identifier` like that, since everything ends up just being a wrapper.

**Comment by rictic** [comment]
Based on the [stage 3 version of the spec](https://github.com/tc39/proposal-class-fields/blob/a1e7bdd3e82c7a081a4e759f3d6904dd0c5a8be7/spec.html#L88):

```
interface FieldDefinition <: Node {
  type: "FieldDefinition";
  name: Identifier | PrivateName;
  init: Expression | null;
  static: boolean;
}

interface PrivateName <: Expression {
  type: "PrivateName";
  name: string;  // must start with #
}

extend interface ClassBody {
    body: [ MethodDefinition | FieldDefinition ];
}
```

**Comment by mroch** [comment]
looks like Babylon has something slightly different than all of the other proposals here:

```
export type PrivateName = NodeBase & {
  type: "PrivateName",
  id: Identifier,
};
```

(see also https://github.com/babel/babylon/pull/698)

for now, I'm going to do the same in Flow, but I'd love to keep moving this discussion forward so estree can agree on something before it gets widely used. Flow implements estree, not the Babylon AST, so we'll move to whatever is decided here.

**Comment by mikesherov** [comment]
@rreverser @hzhu @ariya any thoughts here?

**Comment by hzoo** [comment]
We just did a rename https://github.com/babel/babylon/pull/698, "it's somewhat confusing to have
to use `.name.name` to get the actual string"

**Comment by adrianheine** [comment]
With respect to https://github.com/tc39/proposal-private-methods I'd prefer if being private and being a field would be orthogonal in the AST. So I would prefer @rictic's suggestion over `ClassPrivateProperty`. Instead of `FieldDefinition.name` it should be `FieldDefinition.key` to mirror `MethodDefinition`, though. Also, `FieldDefinition.key` can be any `Expression` and `FieldDefinition` needs a `computed` property. I'd like to prepare a PR for this suggestion.

**Comment by adrianheine** [comment]
One problem with this is that `computed: true, key: PrivateName` is not valid.

**Comment by adrianheine** [comment]
Another open question is the relationship between `PrivateName` and `Identifier`. `PrivateName` cannot extend `Identifier`, since it's not usable everywhere an `Identifier` is allowed. Furthermore, I think we don't need to have an `Identifier` inside `PrivateName`. I don't expected computed private names, so we don't need extensibility there. That would point towards @rictic's proposal (a `PrivateName` is neither an `Expression` nor a `Pattern`, though, and I don't think `name` should contain the `#`):

```js
interface PrivateName {
  type: "PrivateName";
  name: string;  // without #
}
```
