### ISSUE TITLE
Property.key should be an expression

### ISSUE THREAD

**Issue by SrTobi** [estree/estree#187]
Hi,
I don't know if I miss something but shouldn't key of Property be an expression and not only `Identifier | Literal`?

Relevant source:
https://github.com/estree/estree/blame/master/es5.md#L505

Esprima does it correctly:
http://esprima.org/demo/parse.html?code=(%7B%0D%0A%09%5B3%2B3%5D%3A%20%22blub%22%0D%0A%7D)

**Comment by j-f1** [comment]
This is intentional — keys like that weren’t supported in ES5. [The ES2015 ESTree spec](https://github.com/estree/estree/blob/master/es2015.md#expressions) <sup>(you might need to scroll down a little)</sup> has this:
https://github.com/estree/estree/blob/a27003adf4fd7bfad44de9cef372a2eacd527b1c/es2015.md#L134-L139
