### ISSUE TITLE
Should \u2028 and \u2029 affect the location line?

### ISSUE THREAD

**Issue by pvdz** [estree/estree#199]
The spec lists 2028 and 2029 as line terminators, in addition to \n and \r.

https://astexplorer.net/#/gist/15eb31fbb1024faa6f42a4940d8beb4a/555c834d4c371b1ac1cf9c5fbe86e66d75eda015

Babel and Acorn do not seem to increment the line for PS/LS, Esprima, Traceur and Flow do.

I think it should, although some (many?) environments don't consider these chars newlines and will be visually awkward.

**Comment by loganfsmyth** [comment]
I asked about this over in https://esdiscuss.org/topic/expectations-around-line-ending-behavior-for-u-2028-and-u-2029 last year. I think it's a bit frustrating either way, but given that all of the JS engines treat them as line terminators per the spec, I think any ESTree parsers should too. Otherwise you end up with issues where errors thrown by JS parsers could report different lines than V8, SpiderMonkey, and so on. If Babel and Acorn don't handle it, I'd consider it a bug. I know we fixed something around this in Babel a while back, but we must have still missed some cases.

**Comment by pvdz** [comment]
Interesting thread, thanks.
I think I'll just make it optional, while enabled (as in, incrementing the line counter) by default.
And I'll file Babel issues for what I found in a bit.

**Comment by pvdz** [comment]
(Is it desirable to have this sort of stuff mentioned in the estree spec explicitly? I would think so...)
