### ISSUE TITLE
Confusing usage of PropertyDefinition

### ISSUE THREAD

**Issue by 3cp** [estree/estree#239]
In current https://github.com/estree/estree/blob/master/experimental/class-features.md

```js
extend interface ClassBody {
    body: [ MethodDefinition | PropertyDefinition ];
}
```

`PropertyDefinition` is used for the class public fields and private fields. This type was previously known as `FieldDefinition` or `ClassProperty`.

But in ECMA262 standard, `PropertyDefinition` actually has different meaning.
https://tc39.es/ecma262/#prod-ObjectLiteral
`PropertyDefinition` in ECMA262 means property in object literal, which is totally different from class fields.

We noticed this confusion when updating meriyah parser to latest estree spec. https://github.com/meriyah/meriyah/pull/163

Is this difference of `PropertyDefinition` between estree and ECMA262 overlooked?

**Comment by RReverser** [comment]
> Is this difference of `PropertyDefinition` between estree and ECMA262 overlooked?

No, not overlooked, because ESTree was never designed to match ECMAScript naming. Those are two different specs with different priorities.

ECMAScript is a living spec describing abstract syntax & runtime, and can change naming and structure of productions between versions as well as split them up to low-level details, whereas ESTree is its own spec for format for tools & humans with [its own priorities](https://github.com/estree/estree#philosophy).

**Comment by 3cp** [comment]
Thx for the clarification.
