### ISSUE TITLE
extend interface & `<:`

### ISSUE THREAD

**Issue by xp44mm** [estree/estree#274]
Can't understand what `extend interface` and `<:` mean, can anybody explain it?

the `extend interface`
```ts
extend interface Function {
    generator: boolean;
}
```

and `<:`

```ts
interface ForOfStatement <: ForInStatement {
    type: "ForOfStatement";
}
```

**Comment by bradzacher** [comment]
`extend interface` means that you take the original `Function` interface from an older version of the spec, and you augment it with the changes listed.

In your example it's saying that "the AST for this ES version adds the property `generator: boolean` to the `Function` AST node".

---

`X <: Y` means that `X` inherits from `Y`, and it lists the changes / additions.

In your example it's saying that the `FoOfStatement` AST node inherits its properties from the `ForInStatement` AST node, except the `type` property's value should be `'ForOfStatement'` (instead of `'ForInStatement'`)

**Comment by nzakas** [comment]
Nice description 👍
