### ISSUE TITLE
BinaryExpression Tree Balance

### ISSUE THREAD

**Issue by conartist6** [estree/estree#284]
I don't see that the spec dictates tree balance, but all the parsers I can get my hands on behave the same way. Could this be formalized?

E.g for:
```js
2 + 2 + 2
```

All estree parsers I could find produced left-heavy trees:
```json
{
  "type": "BinaryExpression",
  "left": {
    "type": "BinaryExpression",
    "left": {
      "type": "Literal",
      "value": 2
    },
    "right": {
      "type": "Literal",
      "value": 2
    },
    "operator": "+"
  },
  "right": {
    "type": "Literal",
    "value": 2
  },
  "operator": "+"
}
```

**Comment by conartist6** [comment]
Ah my bad, I was misunderstanding how this can happen. The right-heavy tree is actually produced by `2 + (2 + 2)`

**Comment by gibson042** [comment]
It is necessary for e.g. `1 + 2 + "3"` to be interpreted like `(1 + 2) + "3"` rather than `1 + (2 + "3")` and result in `"33"` rather than `"123"`, but [The Syntactic Grammar](https://tc39.es/ecma262/multipage/notational-conventions.html#sec-syntactic-grammar) mentions only "_this stream of input elements is then parsed by a single application of the syntactic grammar_" and AIUI the actual associativity requirements are implicit in productions like <tt>[AdditiveExpression](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#prod-AdditiveExpression) : _AdditiveExpression_ `+` _MultiplicativeExpression_</tt>.
