### ISSUE TITLE
Make `NullLiteral` check easier

### ISSUE THREAD

**Issue by fisker** [estree/estree#297]
Currently, without using `.raw` property (which is not in the spec).

```js
const isNullLiteral = node => node?.type === 'Literal' && node.value === null && !node.regexp && !node.bigint && !node.decimal;
```

This is too long, and not future proof, since `Literal` type may add more values in future.

How about add `.null = true` or `.kind = 'null'`?

**Comment by bradzacher** [comment]
For `hermes-parser` I added a non-standard property `literalType` to make it a discriminated union and to make it easy to determine what type of literal it is.

Works really well as you can switch over the property and know exactly what you're getting.

**Comment by nzakas** [comment]
It doesn't really make sense to add new properties to old nodes because we can't guarantee that people will implement it, which means you'd be stuck checking for the new property and also checking the way you currently do.

I know I say this on a  lot of issues, but ESTree isn't a spec, it's a loose agreement between a handful of implementers to do things a certain way (specifically, Acorn, ESLint, and Babel). As such, it's difficult to go back and change old things because anyone who's not following this repo just won't do it, which means any tools consuming ESTree always need to check for multiple things, effectively negating the intended effect of the addition.

**Comment by fisker** [comment]
> which means you'd be stuck checking for the new property and also checking the way you currently do.

I don't think so, once the parser I use adopt this change, I can use the new way.


> because anyone who's not following this repo just won't do it, 

What if I only care the ones "do"? And I believe parsers will happy to accept this change. If specific parser don't I can abandon it, there are choices nowadays.

**Comment by nzakas** [comment]
If you can get the parade you’re using to change, then you should do that. Implementations can choose to add custom properties. That’s the best way to go for your use case.
