### ISSUE TITLE
Prefixed experimental node types

### ISSUE THREAD

**Issue by nzakas** [estree/estree#95]
Going forward, it seems that there will be a rise in experimental node types via parsers like Babel and dialects like Flow and TypeScript. If tools go on to rely on these experimental node types, it can lead to compatibility problems once the feature is finalized (see: argument defaults and rest params).

I'd like to propose a formal way of flagging a node as experimental via a node type name prefix of `_`, such as `_NamedFooBar` instead of just `NamedFooBar`. This would allow tools to quickly recognize that a node is not formally part of ESTree and be able to react accordingly.

There are probably other ways of handling this, I'm not married to this solution. If just like to figure out some way of doing this to make it easier to create ESTree-compatible ASTs with experimental node types.

Thoughts?

**Comment by impinball** [comment]
@RReverser, @mikesherov, @sebmck?

**Comment by sebmck** [comment]
I do not think it's the responsibility of ESTree to specify the format of nodes that it doesn't specify.

**Comment by impinball** [comment]
I think this is more about a possible ESTree analog to the `text/x-*` (and similar) MIME types or HTML5's hyphenated tags and `data-` attributes, similar in scope. A standard way to express an unspecified, non-standard node type.

**Comment by mikesherov** [comment]
@sebmck seems though that we could easily fix this without too much overhead? For JSX, Flow, etc, I don't think Babel needs to denote these as experimental... I'm only concerned with Nodes that are not yet in JS but are candidates for eventual inclusion. Thoughts?

**Comment by sebmck** [comment]
I don't want to have to bump majors just for a node type change when some becomes stable.

**Comment by impinball** [comment]
To be perfectly honest, I am leaning against, for two reasons: I've yet to see any name collisions, even in Babel, and I don't think there's going to be much more in terms of new syntax added, [considering this recent es-discuss thread](https://esdiscuss.org/topic/the-tragedy-of-the-common-lisp-or-why-large-languages-explode-was-revive-let-blocks). And for the two examples given (default arguments and rest parameters), the problem was with Acorn and Esprima's outputs [differing in structure, nothing to do with name collision](https://github.com/estree/estree/issues/3).

And I agree, @sebmck.

**Comment by mikesherov** [comment]
@sebmck 

> I don't want to have to bump majors just for a node type change.

We don't need to make it backwards incompatible. It would be nice to have a standard property for all nodes called `experimental`. Presence indicates experimental, non presence indicates not experimental. Babel would not have to publish a major version to drop the experimental property from a node.

That's just an example. However, I'd like to not be married to whatever Babel has independently decided a node should be called should it make it into the language.

**Comment by sebmck** [comment]
@mikesherov An `experimental` property adds little value. Non-standard nodes aren't necessarily experimental and what's the point in marking them as such?

**Comment by impinball** [comment]
Besides, I do believe that in the event a non-standard type Babel uses is added under a different name to ESTree's spec, I think @sebmck would definitely deprecate the old one in favor of the newer, standardized one. And if a potential addition would conflict with an existing Babel type, he'd definitely make that known when it's proposed.

**Comment by mikesherov** [comment]
> I  do believe that in the event a non-standard type Babel uses is added under a different name to ESTree's spec, I think @sebmck would definitely deprecate the old one in favor of the newer, standardized one. 

This works for me as long as it works for @sebmck and @nzakas

**Comment by nzakas** [comment]
Okay, just for semantic purposes, assume with I say "experimental" I mean "nonstandard".

Here's the problem: missing custom and standard node types leaves people consuming those node types without any hint that what they're doing may stop working. I don't question @sebmck's methodologies or willingness to do the right thing, I question giving consumers zero indication that what they're using isn't future-safe. 

Again, we already had this issue with default and rest arguments, and that affected a lot of tools that had to be updated to work properly together. Many didn't realize these node types weren't standardized so they hadn't built in any affordances for them.

I think it's shortsighted to think that Babel will be the only tool generating ASTs with custom node types and therefore we can rely on that project doing the right thing to solve this problem. I'd much rather give a space for custom nodes that every project can adhere to in a common way.

So, I'm not satisfied with the "do nothing" approach. If I'm the only one who sees this as a problem, I'll close the issue. I'd just ask everyone to think beyond today's landscape before dismissing this concern.

**Comment by sebmck** [comment]
Enforcing restrictions on non-standard node types is completely out of the question IMO. A node property can just as easily be overlooked and wont effect how consumers use it.

**Comment by sebmck** [comment]
The only place where tool interoperability would be an issue would be with colliding types and if types collide then it's likely that the nodes represent the same thing and should be standardised.

**Comment by RReverser** [comment]
I agree with @nzakas here. Having some standardized way to define non-colliding node types would help a lot if we want to see more compliant AST tools for JavaScript dialects.

I'm just not sure that we need to use some standardized prefix for this as it seems to be a perfect usecase for ES6 symbols. If specific dialect wants to define custom node types that would never collide with others, it can just define node as `{type: MyNodeType}` where `MyNodeType = Symbol('MyNodeType')` and export it for corresponding consumers / transformers.

@nzakas Thoughts?

**Comment by nzakas** [comment]
@sebmck it's not enforcing restrictions, it's asking people to play nice in a global namespace. HTTP uses `X-`, CSS used `-`, etc. Nothing was enforced per se, everyone just asked that everyone else file suit.

For instance, what would be the downside of changing all nonstandard nodes in Babel to be prefixed with  `Babel`?

@RReverser symbols imply ES6-only implementations, which seems a bit too narrow.

**Comment by RReverser** [comment]
@nzakas Not necessarily, polyfills are already pretty good and definitely cover our use-case (no conflicts).

**Comment by sebmck** [comment]
@RReverser Then you have a weird labyrinth of strings and symbol node types which makes it awkward to deal with (non-standard and standard nodes should be treated the same way IMO). If a node becomes standardised then it's not backwards compatible either since it goes from being a symbol to a string which has the same issues as mandating a node type prefix.

@nzakas I'm not bumping majors for an AST change. All the tools that rely on those nodes would need to be updated too. Do you have a specific present scenario in mind? I'm finding it difficult to find the issue with mixing standard and non-standard nodes.

**Comment by RReverser** [comment]
> HTTP uses `x-`

It was considered as anti-pattern later and switched back to regular names.

> For instance, what would be the downside of changing all nonstandard nodes in Babel to be prefixed with Babel?

Which of them are Babel-specific? Flow types? I don't think so. ES7 features? Well, they're just drafts of future ESTree extensions.

P.S. I like the idea in general, but those arguments sound rather not enough.

**Comment by getify** [comment]
I also agree with @nzakas that it would be helpful to have a semi-standardized signifier (of any sort) for a node that isn't standardized (yet). I think a property on the node would be less brittle to future changes than a prefix in the type.

What if instead of prefixing the value, we prefix the property name... like for instance the spec could say "all non-standard nodes should use the `_type` property instead of `type`" or whatever? That way the promotion of a non-standard node to a standard node is simply adding the real `type` property (and perhaps deprecating/removing the old one, maybe at a later time). Seems less brittle to me.

**Comment by nzakas** [comment]
@sebmck this is exactly my point - tools are relying on these nonstandard nodes and may have no idea that they are nonstandard and therefore represent a maintenance issue going forward. Being able to know that there nodes are nonstandard would be huge for tools like ESLint so we can better deal with unexpected nodes when they pop up instead of just failing.

I am also concerned, just to be clear, about naming collisions. Any tool that produces an ESTree-like AST that reaches sufficient ubiquity will create an ecosystem of dependence on those nonstandard nodes, which can make it hard for a lot of tools and for making proper ESTree additions without colliding with already-existing nonstandard nodes. Effectively, at this point, we either a) must standardize the nonstandard node type or b) agree never to use it. That becomes a scalability problem as new syntax is added in misc tools.

If we address this now, we have a shot at heading off the problem.

@RReverser re: HTTP. Meh, I thought that was dumb. Making collisions are a real problem, `X-` will be around forever.

@getify another property doesn't solve the naming collision problem.

**Comment by sebmck** [comment]
@getify Having to special case `node._type || node.type` **everywhere** you need access to the `type` will become quite tedious.

@nzakas 

> I am also concerned, just to be clear, about naming collisions.

I'm still of the opinion, as before, that any collisions should be dealt with separately rather than putting restrictions in the specification. I know this sounds rash and uncooperative but if any formal decision is made on non-standard nodes then Babel is going to opt-out of that portion of the spec. Making third-party nodes second-class citizens is silly IMO and is overstepping the boundaries of what ESTree is.

> Any tool that produces an ESTree-like AST that reaches sufficient ubiquity will create an ecosystem of dependence on those nonstandard nodes, which can make it hard for a lot of tools and for making proper ESTree additions without colliding with already-existing nonstandard nodes.

This fear is premature IMO. Nobody here wants fragmentation, so cooperation on fixing collisions should not be an issue. Possible node collisions should be dealt with at their source, rather than introducing additional complexity and abstraction on node definitions.

> Being able to know that there nodes are nonstandard would be huge for tools like ESLint so we can better deal with unexpected nodes when they pop up instead of just failing.

Why isn't the node type being unknown to ESLint enough? What benefit does namespacing have in this scenario? How does a namespace/prefixes help when ESLint encounters a node it doesn't understand?.

**Comment by mikesherov** [comment]
Let's all remember we live in a *versioned* world here, and don't suffer the same types of issues that unversionable platforms (like the web or javascript) suffer from.

Should an experimental node reach ubiquity and there are changes needed to be made before it lands in ESTree, then @sebmck can publish a new major version of Babel correcting the node, and anyone who wants to follow the new version of Babel, they have to upgrade and fix. At least that's how I read @sebmck saying:

> This fear is premature IMO. Nobody here wants fragmentation, so cooperation on fixing collisions should not be an issue. 

I'd prefer that world than breaking nodes simply by them becoming standardized. Like Babel et al should not have to release a breaking change to unprefix. That strategy only works (and poorly at that) when you are bound to not break the web.

**Comment by nzakas** [comment]
> I'm still of the opinion, as before, that any collisions should be dealt with separately rather than putting restrictions in the specification. 

Again, this is a scaling problem. If it was once or twice, no biggie. But it's going to be constant and ongoing. 

>  I know this sounds rash and uncooperative but if any formal decision is made on non-standard nodes then Babel is going to opt-out of that portion of the spec. 

Yes, it does. This is exactly the scenario that leads to forced-standards due to ubiquity and limits the types of changes that can be made in the future. We will have effectively delegated creation of new node types to projects like Babel. Maybe everyone is fine with that, but it should be an explicit agreement and not an accident of circumstance.

@mikesherov 

> Let's all remember we live in a versioned world here, and don't suffer the same types of issues that unversionable platforms (like the web or javascript) suffer from.

I think is a dangerous line of reasoning. There is an ecosystem around ESTree tools, and having gone through this process of fixing several of them, this wave of tool updates and synchronizations is a big pain and shouldn't be treated as a simple versioning problem. 

But if @sebmck, one of the primary implementors of nonstandard nodes won't agree to any proposal along the lines I've suggested, then there's really no point in continuing this discussion.

So, I've said my piece on this, take it for what you will.  If I'm really the only one who sees a problem here, feel free to close this issue as won't fix. I'll be disappointed, but life will go on. :)

**Comment by mikesherov** [comment]
> So, I've said my piece on this, take it for what you will. If I'm really the only one who sees a problem here, feel free to close this issue as won't fix. I'll be disappointed, but life will go on. :)

I wish we all had this attitude :-)

I don't think it's a forgone conclusion not to do this.

**Comment by getify** [comment]
I'm not going to fight for `_type` because I don't care about this particular bikeshed -- was just an idea to address some of the concerns. So this message can be dropped/ignored if no one sees it the same as me. But I do want to address two replies briefly:

> another property doesn't solve the naming collision problem.

Depends on what naming collision you're worried about.

If you're worried about two different tools each producing a non-standard node of the same `_type` value but being incompatible... no, it doesn't prevent that. But nothing does. The spec can't say "you have to use a globally unique prefix" because enforcing such uniqueness is pragmatically impossible. So collision is possible.

But it does, I think, significantly reduce the risk of collision between a non-standard node and an eventually standardized, but incompatible, node of the same type. If the standard says you must not change from `_type` to `type` until the spec agrees the node is standardized, then a conforming tool will have to keep its non-standard version at `_type` and either change it to match standard node before using `type`, or create another node that matches the standard and phase out their old one.

That's the whole reason I suggested prefixing the property name, because it allows coexistence of the old (and deprecated and going away) node with the new standardized node. Co-existence with a deprecation phase-out rather than an abrupt breaking change reduces the tension of "bumping major versions", coordination of tools, etc.

Also, "promotion" from non-standard to standard can be as simple as changing from `_type` to `type`.

> Having to special case node._type || node.type everywhere you need access to the type will become quite tedious.

I don't envision that you'd write that kind of code. Doesn't make sense to me. I would think it'd be more like:

```js
if (node._type) {
   // .. handle any non-standard node types that this tool "knows" about
}
else {
  // handle all the standard node types
}
```

If it's a non-standard node, it doesn't make much sense for it to flow into the exact same code as your standard nodes. By definition, non-standard deserves special handling.

And once the node is changed from `_type` to `type` to be standardized, you just move the handling code from the `if` branch to the `else` branch.

**Comment by sebmck** [comment]
I don't really want an AST spec to dictate my architecture and release cycle. If you have specific concerns about the way Babel is defining non-standard nodes then I'd be more than happy to discuss it in a Babel channel.

FWIW, I did propose/create the [experimental](https://github.com/estree/estree/tree/master/experimental) folder for this specific purpose, to provide node definitions for early proposals. I've either not bought new node definitions in for consideration due to time constraints or lack of confidence in their structure and inclusion in ECMAScript. Also important to note then when the notion of standardising non-standard/ES nodes in ESTree was bought up previously (ie. #44) there was heavy backlash.

**Comment by mikesherov** [comment]
> I don't really want an AST spec to dictate my architecture and release cycle.

No one wants to dictate anything. This whole "standard" is an agreement and no one is *bound* to anything. But, we are here to propose and bikeshed solutions for maximum productivity of the entire ecosystem. 

Having a problem with *babel* specifically is not the point but rather a good case study that happens to be run by a participating member.

FWIW, I'm +1 on experimental definitions being loosely specced.

**Comment by sebmck** [comment]
I know noone is bound to anything but I'd rather not have to deviate from the specification because if I do then I'm afraid it'll be a slippery slope and larger deviations will be made.

**Comment by nzakas** [comment]
Closing as we aren't doing this.
